// templates/llm/app/src/react/components/ContractCard.tsx
import type { JSX } from "react";

interface Props {
  haveCoin: boolean | null;
  busy: boolean;
  canWrite: boolean;
  onRefresh: () => void;
  onAsk: () => void;
}

export function ContractCard({
  haveCoin,
  busy,
  canWrite,
  onRefresh,
  onAsk,
}: Props): JSX.Element {
  return (
    <section className="card">
      <p>
        <strong>Wizard has coin:</strong>{" "}
        {haveCoin === null ? <span className="muted">unknown</span> : haveCoin ? "yes" : "no"}
      </p>
      <p style={{ display: "flex", gap: "0.5rem" }}>
        <button onClick={onRefresh} disabled={busy}>
          {busy ? "Refreshing…" : "Read (refresh)"}
        </button>
        <button onClick={onAsk} disabled={busy || !canWrite}>
          Ask for the coin
        </button>
      </p>
    </section>
  );
}

// templates/llm/app/src/vue/components/ContractCard.vue
<script setup lang="ts">
defineProps<{
  haveCoin: boolean | null;
  busy: boolean;
  canWrite: boolean;
}>();

defineEmits<{
  (e: "refresh"): void;
  (e: "ask"): void;
}>();
</script>

<template>
  <section class="card">
    <p>
      <strong>Wizard has coin:</strong>
      <span v-if="haveCoin === null" class="muted">unknown</span>
      <span v-else>{{ haveCoin ? "yes" : "no" }}</span>
    </p>
    <p style="display: flex; gap: 0.5rem">
      <button @click="$emit('refresh')" :disabled="busy">
        {{ busy ? "Refreshing…" : "Read (refresh)" }}
      </button>
      <button @click="$emit('ask')" :disabled="busy || !canWrite">
        Ask for the coin
      </button>
    </p>
  </section>
</template>
