// templates/llm/app/src/vue/App.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import ContractCard from "./components/ContractCard.vue";
import { readClient, writeClient, type Network } from "./lib/genlayer";
import { useWallet, hasWallet } from "./lib/wallet";

const CONTRACT_ADDRESS = (import.meta.env.VITE_CONTRACT_ADDRESS ?? "") as `0x${string}`;
const NETWORK = ((import.meta.env.VITE_NETWORK as Network) || "studionet") as Network;

const { address, connecting, error: walletError, connect, disconnect } = useWallet();

const haveCoin = ref<boolean | null>(null);
const busy = ref(false);
const error = ref<string | null>(null);

async function refresh() {
  if (!CONTRACT_ADDRESS) return;
  busy.value = true;
  error.value = null;
  try {
    const client = readClient(NETWORK);
    const result = await client.readContract({
      address: CONTRACT_ADDRESS,
      functionName: "get_have_coin",
      args: [],
    });
    haveCoin.value = Boolean(result);
  } catch (e) {
    error.value = (e as Error).message;
  } finally {
    busy.value = false;
  }
}

async function askForCoin() {
  if (!CONTRACT_ADDRESS) return;
  if (!address.value) {
    error.value = "Connect a wallet first.";
    return;
  }
  busy.value = true;
  error.value = null;
  try {
    const client = writeClient(NETWORK, address.value);
    await client.connect(NETWORK);
    await client.writeContract({
      address: CONTRACT_ADDRESS,
      functionName: "ask_for_coin",
      args: ["Please give me the coin."],
      value: BigInt(0),
    });
    await refresh();
  } catch (e) {
    error.value = (e as Error).message;
  } finally {
    busy.value = false;
  }
}

onMounted(() => {
  refresh();
});
</script>

<template>
  <main>
    <h1>__PROJECT_NAME__</h1>

    <section class="card">
      <p>
        <strong>Wallet:</strong>
        <code v-if="address">{{ address }}</code>
        <span v-else class="muted">not connected</span>
      </p>
      <button v-if="!address" @click="connect" :disabled="connecting || !hasWallet()">
        {{ connecting ? "Connecting…" : hasWallet() ? "Connect wallet" : "No wallet detected" }}
      </button>
      <button v-else @click="disconnect">Disconnect</button>
    </section>

    <ContractCard
      :have-coin="haveCoin"
      :busy="busy"
      :can-write="Boolean(address)"
      @refresh="refresh"
      @ask="askForCoin"
    />

    <p v-if="walletError" class="err"><strong>Wallet error:</strong> {{ walletError }}</p>
    <p v-if="error" class="err"><strong>Error:</strong> {{ error }}</p>
  </main>
</template>

// templates/llm/app/src/react/App.tsx
import { useEffect, useState } from "react";
import { ContractCard } from "./components/ContractCard";
import { readClient, writeClient, wizardAbi, type Network } from "./lib/genlayer";
import { useWallet, hasWallet } from "./lib/wallet";

const CONTRACT_ADDRESS = (import.meta.env.VITE_CONTRACT_ADDRESS ?? "") as `0x${string}`;
const NETWORK: Network =
  ((import.meta.env.VITE_NETWORK as Network) || "studionet") as Network;

export function App() {
  const wallet = useWallet();
  const [haveCoin, setHaveCoin] = useState<boolean | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // 1 read on mount: get_have_coin
  const refresh = async () => {
    if (!CONTRACT_ADDRESS) return;
    setBusy(true);
    setError(null);
    try {
      const client = readClient(NETWORK);
      const result = await client.readContract({
        address: CONTRACT_ADDRESS,
        functionName: "get_have_coin",
        args: [],
      });
      setHaveCoin(Boolean(result));
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  };

  // 1 write: ask_for_coin
  const askForCoin = async () => {
    if (!CONTRACT_ADDRESS) return;
    if (!wallet.state.address) {
      setError("Connect a wallet first.");
      return;
    }
    setBusy(true);
    setError(null);
    try {
      const client = writeClient(NETWORK, wallet.state.address);
      // Switch the wallet to the configured network before signing.
      await client.connect(NETWORK);
      const txHash = await client.writeContract({
        address: CONTRACT_ADDRESS,
        functionName: "ask_for_coin",
        args: ["Please give me the coin."],
        value: BigInt(0),
      });
      // Read back via the read client (no wallet signature needed for the
      // receipt poll). Refresh state after the next block.
      await refresh();
      void txHash;
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  };

  useEffect(() => {
    refresh();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (!CONTRACT_ADDRESS) {
    return (
      <main>
        <h1>__PROJECT_NAME__</h1>
        <p className="muted">
          Set <code>VITE_CONTRACT_ADDRESS</code> in <code>app/.env</code> after
          deploying the contract.
        </p>
      </main>
    );
  }

  return (
    <main>
      <h1>__PROJECT_NAME__</h1>

      <section className="card">
        <p>
          <strong>Wallet:</strong>{" "}
          {wallet.state.address ? (
            <code>{wallet.state.address}</code>
          ) : (
            <span className="muted">not connected</span>
          )}
        </p>
        {!wallet.state.address ? (
          <button onClick={wallet.connect} disabled={wallet.state.connecting || !hasWallet()}>
            {wallet.state.connecting ? "Connecting…" : hasWallet() ? "Connect wallet" : "No wallet detected"}
          </button>
        ) : (
          <button onClick={wallet.disconnect}>Disconnect</button>
        )}
      </section>

      <ContractCard
        haveCoin={haveCoin}
        busy={busy}
        onRefresh={refresh}
        onAsk={askForCoin}
        canWrite={Boolean(wallet.state.address)}
      />

      {error && (
        <p className="err">
          <strong>Error:</strong> {error}
        </p>
      )}
    </main>
  );
}
